site_name: "spatial-graph"
site_url: https://github.com/funkelab/spatial_graph
site_description: >-
  High performance spatial graph library for Python
# Repository
repo_name: funkelab/spatial_graph
repo_url: https://github.com/funkelab/spatial_graph

theme:

  name: material
  palette:
    scheme: default
    primary: pink
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.instant

plugins:
  - search
  - api-autonav:
      modules: ["src/spatial_graph"]
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_section_style: list # or "table"
            docstring_style: "numpy"
            filters: ["!^_"]
            heading_level: 1
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true
